@startuml

title SOLID Dependency Inversion

interface Database {
  +save(data: string): void
}

class PostgreSqlDatabase {
  +save(data: string): void
}

class OracleDatabase {
  +save(data: string): void
}

class DataService {
  -database: Database
  +DataService(database: Database)
  +saveData(data: string): void
}

DataService o- Database
PostgreSqlDatabase -up-|> Database
OracleDatabase -up-|> Database

note top of DataService
  "The high-level class depends on abstraction, not on specific implementation classes of the lower level"
end note

@enduml