@startuml

interface Car {
currentSpeed()
}

class Inspector {
}

class Driver {
}

class DriversWife {
}

interface InspectorCar {
currentSpeed()
turnOnSiren()
checkNumber()
}

interface DriverCar {
currentSpeed()
playMusic()
handbrake()
rudder()
pedals()
}


interface WifesCar {
currentSpeed()
playMusic()
}


Car <|-- InspectorCar
Car <|-- DriverCar
Car <|-- WifesCar
InspectorCar <.. Inspector
DriverCar <.. Driver
WifesCar <.. DriversWife

@enduml