@startuml

skinparam class {
BackgroundColor<< set >> palegreen
BackgroundColor<<queue>> yellow
BackgroundColor<<list>> orangered
}

interface Iterable
interface Collection extends Iterable

abstract class AbstractCollection implements Collection

interface Set << set >> extends Collection
abstract class AbstractSet extends AbstractCollection implements Set
class HashSet << set >> extends AbstractSet implements Set
class LinkedHashSet << set >> extends HashSet implements Set
interface SortedSet << set >> extends Set
interface NavigableSet << set >> extends SortedSet
class TreeSet << set >> extends AbstractSet implements NavigableSet

interface Queue << queue >> extends Collection
interface Deque << queue >> extends Queue

interface List << list >> extends Collection
abstract class AbstractList extends AbstractCollection implements List
abstract class AbstractSequentialList extends AbstractList
class LinkedList << list >> #orange extends AbstractSequentialList implements List, Deque
class ArrayList << list >> extends AbstractList implements List
class Vector << list >> extends AbstractList implements List
class Stack << list >> extends Vector

@enduml