@startuml

title Maps Hierarchy

skinparam class {
BackgroundColor orange
}

interface Map
abstract class Dictionary
abstract class AbstractMap implements Map

interface SortedMap extends Map
interface NavigableMap extends SortedMap

class Hashtable extends Dictionary implements Map
class TreeMap extends AbstractMap implements NavigableMap
class HashMap extends AbstractMap implements Map

@enduml